import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Grocee',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className='mx-auto max-w-[1440px]'>{children}</body>
    </html>
  )
}
